pal_swap_init_system(shd_pal_swapper)
ini_open("saveData.ini")
global.deserthighscore = ini_read_string("Highscore", "desert", 0)
global.mansionhighscore = ini_read_string("Highscore", "mansion", 0)
global.factoryhighscore = ini_read_string("Highscore", "factory", 0)
global.sewerhighscore = ini_read_string("Highscore", "sewer", 0)
global.freezerhighscore = ini_read_string("Highscore", "freezer", 0)
global.entrancehighscore = ini_read_string("Highscore", "entrance", 0)
global.medievalhighscore = ini_read_string("Highscore", "medieval", 0)
global.deserttoppin1 = ini_read_string("Toppin", "desert1", 0)
global.deserttoppin2 = ini_read_string("Toppin", "desert2", 0)
global.deserttoppin3 = ini_read_string("Toppin", "desert3", 0)
global.deserttoppin4 = ini_read_string("Toppin", "desert4", 0)
global.deserttoppin5 = ini_read_string("Toppin", "desert5", 0)
global.mansiontoppin1 = ini_read_string("Toppin", "mansion1", 0)
global.mansiontoppin2 = ini_read_string("Toppin", "mansion2", 0)
global.mansiontoppin3 = ini_read_string("Toppin", "mansion3", 0)
global.mansiontoppin4 = ini_read_string("Toppin", "mansion4", 0)
global.mansiontoppin5 = ini_read_string("Toppin", "mansion5", 0)
global.factorytoppin1 = ini_read_string("Toppin", "factory1", 0)
global.factorytoppin2 = ini_read_string("Toppin", "factory2", 0)
global.factorytoppin3 = ini_read_string("Toppin", "factory3", 0)
global.factorytoppin4 = ini_read_string("Toppin", "factory4", 0)
global.factorytoppin5 = ini_read_string("Toppin", "factory5", 0)
global.sewertoppin1 = ini_read_string("Toppin", "sewer1", 0)
global.sewertoppin2 = ini_read_string("Toppin", "sewer2", 0)
global.sewertoppin3 = ini_read_string("Toppin", "sewer3", 0)
global.sewertoppin4 = ini_read_string("Toppin", "sewer4", 0)
global.sewertoppin5 = ini_read_string("Toppin", "sewer5", 0)
global.freezertoppin1 = ini_read_string("Toppin", "freezer1", 0)
global.freezertoppin2 = ini_read_string("Toppin", "freezer2", 0)
global.freezertoppin3 = ini_read_string("Toppin", "freezer3", 0)
global.freezertoppin4 = ini_read_string("Toppin", "freezer4", 0)
global.freezertoppin5 = ini_read_string("Toppin", "freezer5", 0)
global.entrancetoppin1 = ini_read_string("Toppin", "entrance1", 0)
global.entrancetoppin2 = ini_read_string("Toppin", "entrance2", 0)
global.entrancetoppin3 = ini_read_string("Toppin", "entrance3", 0)
global.entrancetoppin4 = ini_read_string("Toppin", "entrance4", 0)
global.entrancetoppin5 = ini_read_string("Toppin", "entrance5", 0)
global.medievaltoppin1 = ini_read_string("Toppin", "medieval1", 0)
global.medievaltoppin2 = ini_read_string("Toppin", "medieval2", 0)
global.medievaltoppin3 = ini_read_string("Toppin", "medieval3", 0)
global.medievaltoppin4 = ini_read_string("Toppin", "medieval4", 0)
global.medievaltoppin5 = ini_read_string("Toppin", "medieval5", 0)
ini_close()

enum states {
    normal = 0,
    finishingblow = 2,
    tumble = 1,
    titlescreen = 7,
    ejected = 3,
    firemouth = 6,
    fireass = 5,
    transitioncutscene = 4,
    hookshot = 8,
    slap = 11,
    tacklecharge = 9,
    cheesepep = 12,
    cheeseball = 10,
    cheesepepstick = 13,
    boxxedpep = 14,
    pistolaim = 15,
    climbwall = 16,
    knightpepslopes = 17,
    portal = 18,
    secondjump = 19,
    chainsawbump = 20,
    handstandjump = 21,
    gottreasure = 22,
    knightpep = 23,
    knightpepattack = 24,
    meteorpep = 25,
    bombpep = 26,
    grabbing = 27,
    chainsawpogo = 28,
    shotgunjump = 29,
    stunned = 30,
    highjump = 31,
    chainsaw = 32,
    facestomp = 33,
    timesup = 35,
    machroll = 36,
    pistol = 38,
    shotgun = 37,
    machfreefall = 39,
    throwstate = 40,
    superslam = 42,
    slam = 41,
    skateboard = 43,
    grind = 44,
    grab = 45,
    punch = 46,
    backkick = 47,
    uppunch = 48,
    shoulder = 49,
    backbreaker = 50,
    bossdefeat = 51,
    bossintro = 53,
    smirk = 61,
    pizzathrow = 52,
    gameover = 54,
    Sjumpland = 91,
    freefallprep = 90,
    runonball = 88,
    boulder = 87,
    keyget = 55,
    tackle = 56,
    slipnslide = 59,
    ladder = 58,
    jump = 57,
    victory = 63,
    comingoutdoor = 60,
    Sjump = 62,
    Sjumpprep = 64,
    crouch = 65,
    crouchjump = 66,
    crouchslide = 67,
    mach1 = 68,
    mach2 = 69,
    mach3 = 89,
    machslide = 70,
    bump = 71,
    hurt = 72,
    freefall = 73,
    freefallland = 76,
    hang = 74,
    door = 77,
    barrelnormal = 83,
    barrelfall = 82,
    barrelmach1 = 81,
    barrelmach2 = 80,
    barrelfloat = 79,
    barrelcrouch = 78,
    barrelslipnslide = 84,
    barrelroll = 85,
    current = 86,
    idle = 92,
    turn = 96,
    walk = 100,
    land = 102,
    hit = 103,
    stun = 104,
    throw2 = 95,
    grabbed = 107,
}
